In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords

In [2]:
data = pd.read_csv("data/hepsiburada_balanced_300k.csv")

In [3]:
data.head()

                                       combined_text  label
0                                    İki Yıldız. iyi      0
1  Bir Yıldız. kargo sorunsuz geldi ama tam 1 haf...      0
2  Kokusu dışında iş görür. Çok fazla koku yapıyo...      0
3  kötü. saat içinden çıkıyor beklediğim gibi kal...      0
4  Çok kötü.... Almayın çok kötü boşa para verirs...      0

In [4]:
data["label"].value_counts()

label
0    100000
1    100000
2    100000
Name: count, dtype: int64

In [5]:
data[data["label"] == 1]

                                            combined_text  label
100000  WiFi Kurana Aşk Olsun. Bilgisayarlarla içli dı...      1
100001  Kalite beklemeyene iş görür çözüm.. Ürün klavy...      1
100002  ERYILDIZ RAYLI ÇÖP KOVASI . ÜRÜN ELİME ÇABUK U...      1
100003  vasatın altıda. zorlu kış şartlarında denedim ...      1
100004  Lava tava. Teşekkürler Tava beklentimizi karşı...      1
...                                                   ...    ...
199995  detay. Arkadaşlar hangi teyp le kullandınız ön...      1
199996  Huawei p20. Telefon çok güzel paketleme iyi ço...      1
199997  Gerçekten etkili. doğumdan hemen sonra başladı...      1
199998  Fiyat performans iyi. Sağlam pratik Fiyatve pe...      1
199999  güzel. 4 tane yastık söyledim kısa sürede elim...      1

[100000 rows x 2 columns]

In [6]:
data[data["label"] == 2]

                                            combined_text  label
200000  Kesinlikle prima. Ben bugüne kadar bütün marka...      2
200001                  iyi. Ürün paketleme kargolama iyi      2
200002        Dört Yıldız. Güzel bir ürün Kullanımı rahat      2
200003  Beş Yıldız. Harika bir ürün herkese tavsiye ed...      2
200004  Engelli Kedimin Yardımcısı. 13 aylık engelli k...      2
...                                                   ...    ...
299995  Sony. Ürünüm bu gun geldi bekledigimdenden guz...      2
299996  Çok Şık bir ürün. Kutusunun hediye paketi ve h...      2
299997  Kaçırmayın. 4 aylık bebeğim var daha yeni aldı...      2
299998  Beş Yıldız. Beklentimi karşıladı Dış sesleri o...      2
299999  Hızlı ve güvenilir . Hızlı kargo güvenilir alı...      2

[100000 rows x 2 columns]

In [7]:
data = data[data["label"] != 1]

data["label"].value_counts()

label
0    100000
2    100000
Name: count, dtype: int64

In [8]:
data["label"] = data["label"].map({
    0: 0,
    2: 1
})

data["label"].value_counts()

label
0    100000
1    100000
Name: count, dtype: int64

In [9]:
data.head()

                                       combined_text  label
0                                    İki Yıldız. iyi      0
1  Bir Yıldız. kargo sorunsuz geldi ama tam 1 haf...      0
2  Kokusu dışında iş görür. Çok fazla koku yapıyo...      0
3  kötü. saat içinden çıkıyor beklediğim gibi kal...      0
4  Çok kötü.... Almayın çok kötü boşa para verirs...      0

In [10]:
def clean_text(text):
    if not isinstance(text, str):
        return ""
    
    text = text.replace('İ', 'i').replace('I','ı').lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = text.strip()

    return text

In [11]:
sentiment_preserving_words = {
    'değil', 'yok', 'hayır', 'ama', 'fakat', 'ancak', 'lakin', 'asla', 'hiç', 
    'en', 'çok', 'daha', 'pek', 'gayet', 'oldukça', 'aşırı', 'az', 'fazla', 
    'yeterli', 'eksik', 'maalesef', 'zira', 'çünkü', 'rağmen', 'belki'
}

nltk.download('stopwords')
tr_stopwords = set(stopwords.words("turkish"))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tyill\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [12]:
tr_stopwords

{'acaba',
 'ama',
 'aslında',
 'az',
 'bazı',
 'belki',
 'biri',
 'birkaç',
 'birşey',
 'biz',
 'bu',
 'da',
 'daha',
 'de',
 'defa',
 'diye',
 'en',
 'eğer',
 'gibi',
 'hem',
 'hep',
 'hepsi',
 'her',
 'hiç',
 'ile',
 'ise',
 'için',
 'kez',
 'ki',
 'kim',
 'mu',
 'mü',
 'mı',
 'nasıl',
 'ne',
 'neden',
 'nerde',
 'nerede',
 'nereye',
 'niye',
 'niçin',
 'o',
 'sanki',
 'siz',
 'tüm',
 've',
 'veya',
 'ya',
 'yani',
 'çok',
 'çünkü',
 'şey',
 'şu'}

In [13]:
len(tr_stopwords)

53

In [14]:
tr_stopwords = tr_stopwords - sentiment_preserving_words
len(tr_stopwords)

45

In [15]:
def stopwords_clear(text):
        words = text.split()
        clean_words = [w for w in words if w not in tr_stopwords]
        return " ".join(clean_words)

In [16]:
data['clean_text'] = data['combined_text'].apply(lambda x: stopwords_clear(clean_text(x)))

In [17]:
data[["combined_text", "clean_text"]]

,combined_text,clean_text
0,İki Yıldız. iyi,iki yıldız iyi
1,Bir Yıldız. kargo sorunsuz geldi ama tam 1 haf...,bir yıldız kargo sorunsuz geldi ama tam haftad...
2,Kokusu dışında iş görür. Çok fazla koku yapıyo...,kokusu dışında iş görür çok fazla koku yapıyor...
3,kötü. saat içinden çıkıyor beklediğim gibi kal...,kötü saat içinden çıkıyor beklediğim kaliteli ...
4,Çok kötü.... Almayın çok kötü boşa para verirs...,çok kötü almayın çok kötü boşa para verirsiniz...
...,...,...
299995,Sony. Ürünüm bu gun geldi bekledigimdenden guz...,sony ürünüm gun geldi bekledigimdenden guzel c...
299996,Çok Şık bir ürün. Kutusunun hediye paketi ve h...,çok şık bir ürün kutusunun hediye paketi hediy...
299997,Kaçırmayın. 4 aylık bebeğim var daha yeni aldı...,kaçırmayın aylık bebeğim var daha yeni aldım k...
299998,Beş Yıldız. Beklentimi karşıladı Dış sesleri o...,beş yıldız beklentimi karşıladı dış sesleri ol...
299999,Hızlı ve güvenilir . Hızlı kargo güvenilir alı...,hızlı güvenilir hızlı kargo güvenilir alışveri...

In [18]:
data.head()

,combined_text,label,clean_text
0,İki Yıldız. iyi,0,iki yıldız iyi
1,Bir Yıldız. kargo sorunsuz geldi ama tam 1 haf...,0,bir yıldız kargo sorunsuz geldi ama tam haftad...
2,Kokusu dışında iş görür. Çok fazla koku yapıyo...,0,kokusu dışında iş görür çok fazla koku yapıyor...
3,kötü. saat içinden çıkıyor beklediğim gibi kal...,0,kötü saat içinden çıkıyor beklediğim kaliteli ...
4,Çok kötü.... Almayın çok kötü boşa para verirs...,0,çok kötü almayın çok kötü boşa para verirsiniz...

In [19]:
data = data.drop(columns="combined_text", axis=1)
data.head()

   label                                         clean_text
0      0                                     iki yıldız iyi
1      0  bir yıldız kargo sorunsuz geldi ama tam haftad...
2      0  kokusu dışında iş görür çok fazla koku yapıyor...
3      0  kötü saat içinden çıkıyor beklediğim kaliteli ...
4      0  çok kötü almayın çok kötü boşa para verirsiniz...

In [20]:
data.to_csv("clean_data/temiz_turkce_data.csv", index=False)
print("Türkçe veriseti kaydedildi")

Türkçe veriseti kaydedildi